# -*- coding: utf-8 -*-
"""pandas_for_dataanalyst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1seHKdtjWlHRAWSeMZv-H9-StmUk0XOA4
"""

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")

print(df)
df.head()

display(df)

df.describe()

df.tail(4)

df.head(5)

df.index= df['Day']



df

for index,rows in df.iterrows():
  print(rows["Day"])

for index, row in df.iterrows():
  print(index,row["Coffee Type"])

df = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv")

df

df[(df["height_cm"] >215)]

df[(df["name"]=="Zhou Qi") & ( df ["born_country"]=="CHN")]



df

df[(df['born_country'] == "USA") & (df['height_cm'] > 215)]

df[df["name"].str.contains("keith|patrick",case=False)]

df [df['born_country'].isin(["USA","FRA","GBR"]  ) & (df["name"].str.startswith("keith"))]

df